name: Go Build

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests to the main branch
  workflow_dispatch:  # This enables manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the operating system to run on

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'  # Change this to the Go version you need

    - name: Build main.go
      run: go build main.go  # Command to build only main.go

    - name: Run the application (optional)
      run: ./main  # Optional step to run the application after building
